### ISSUE TITLE
Migrations.sol constructor call has more params than in definition

### ISSUE THREAD

**Issue by ctapang** [JoinColony/colonySale#31]
In colonySale/contracts/Migrations.sol, in function upgrade, line 20, the call to the Migrations constructor has a parameter, and it doesn't use the "new" keyword. Is this allowed, or am I missing something? If this is allowed, how is the parameter used by the constructor?

**Comment by area** [comment]
At first glance, I can see that this does look like a constructor call, but is actually a type conversion from `address` to `Migrations` so that  `upgraded.setCompleted` can be called on the next line. You can see this being done in [examples in the Solidity documentation](https://solidity.readthedocs.io/en/develop/contracts.html#creating-contracts) which might help to make this clear.

The way this function should be used is by creating the new Migrations contract with another (unrelated) transaction, and then call the `upgrade` function, passing the address of the new contract as the argument.

I note that this contract actually comes from [http://truffleframework.com/](Truffle), though, so I'm going to close this issue and if you want further clarification, I suggest asking in their [Gitter](https://gitter.im/ConsenSys/truffle) which is usually full of helpful people. Unfortunately, some of them might be distracted by Devcon this week, so you might have to be patient!

**Comment by ctapang** [comment]
Thank you! I understand it now. It's casting the address parameter, not creating a new Migrations.
